branch-defaults:
  master:
    environment: $MASTER-api-movies
global:
  application_name: api-movies
  default_ec2_keyname: ApiMovies
  default_platform: Docker running on 64bit Amazon Linux/2.12.9
  default_region: eu-west-1
  sc: git